### ISSUE TITLE
FYI: get_iplayer does not use rtmpdump

### ISSUE THREAD

**Issue by dinkypumpkin** [llewelld/getiplay#2]
Unless you need rtmpdump for some other reason, you can safely remove it from your package.

**Comment by llewelld** [comment]
Ah great, good catch, thank you. I'm sure it was needed when I first started using get_iplayer, so I suppose it's been removed as a requirement since?

**Comment by llewelld** [comment]
Set up branch [remove-rtmpdump](/llewelld/getiplay/tree/remove-rtmpdump) for the fix.

**Comment by llewelld** [comment]
Addressed by pull request #3.
