### ISSUE TITLE
Make replay/skip duration configurable

### ISSUE THREAD

**Issue by llewelld** [llewelld/getiplay#73]
Currently hitting the replay or skip buttons moves the play position back or forwards by 10 seconds respectively. The length of time should be configurable.

If the value is configurable the current icons will need changing, since they currently say -10s and +10s. The could simply be changed to have - and + instead.

**Comment by revad** [comment]
Better - if it can be done - would be to have more than the two buttons. Or short/long taps. Or gestures. Whatever is possible. 

I often skip through radio programmes using mplayer keyboard commands (in a terminal):
LEFT and RIGHT - Seek backward/forward 10 seconds.
UP and DOWN - Seek forward/backward 1 minute.
PGUP and PGDWN - Seek forward/backward 10 minutes.

**Comment by llewelld** [comment]
Screen space is the big problem when it comes to adding extra buttons. It feels like gestures should be the 'Jolla Way', but I think short/long taps is the more realistic approach to this.

**Comment by llewelld** [comment]
Created branch [73-replay-skip-duration](https://github.com/llewelld/getiplay/tree/73-replay-skip-duration) for this.
